# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contact.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ContactAdmin(object):
    def setupUi(self, ContactAdmin):
        ContactAdmin.setObjectName("ContactAdmin")
        ContactAdmin.setEnabled(True)
        ContactAdmin.resize(523, 479)
        self.verticalLayoutWidget = QtWidgets.QWidget(ContactAdmin)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 461, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.admin_email_label = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.admin_email_label.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.admin_email_label.setFont(font)
        self.admin_email_label.setObjectName("admin_email_label")
        self.verticalLayout.addWidget(self.admin_email_label)
        self.email_title_label = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.email_title_label.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.email_title_label.setFont(font)
        self.email_title_label.setObjectName("email_title_label")
        self.verticalLayout.addWidget(self.email_title_label)
        self.email_content_label = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.email_content_label.setFont(font)
        self.email_content_label.setPlainText("")
        self.email_content_label.setObjectName("email_content_label")
        self.verticalLayout.addWidget(self.email_content_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.required_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.required_label.setFont(font)
        self.required_label.setObjectName("required_label")
        self.horizontalLayout.addWidget(self.required_label)
        self.name_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout.addWidget(self.name_label)
        self.sender_name_field = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.sender_name_field.setFont(font)
        self.sender_name_field.setInputMask("")
        self.sender_name_field.setText("")
        self.sender_name_field.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sender_name_field.setObjectName("sender_name_field")
        self.horizontalLayout.addWidget(self.sender_name_field)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.date_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.date_label.setFont(font)
        self.date_label.setObjectName("date_label")
        self.horizontalLayout_2.addWidget(self.date_label)
        self.current_date_field = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.current_date_field.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.current_date_field.setFont(font)
        self.current_date_field.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.current_date_field.setObjectName("current_date_field")
        self.horizontalLayout_2.addWidget(self.current_date_field)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.submit_btn = QtWidgets.QPushButton(ContactAdmin)
        self.submit_btn.setGeometry(QtCore.QRect(410, 430, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.submit_btn.setFont(font)
        self.submit_btn.setObjectName("submit_btn")
        self.cancel_btn = QtWidgets.QPushButton(ContactAdmin)
        self.cancel_btn.setGeometry(QtCore.QRect(320, 430, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setObjectName("cancel_btn")

        self.retranslateUi(ContactAdmin)
        self.cancel_btn.clicked.connect(ContactAdmin.close)
        QtCore.QMetaObject.connectSlotsByName(ContactAdmin)

    def retranslateUi(self, ContactAdmin):
        _translate = QtCore.QCoreApplication.translate
        ContactAdmin.setWindowTitle(_translate("ContactAdmin", "Send Email To Admin"))
        self.admin_email_label.setText(_translate("ContactAdmin", "yingjoy906@gmail.com"))
        self.email_title_label.setText(_translate("ContactAdmin", "From FaceR Client: "))
        self.required_label.setText(_translate("ContactAdmin", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">*</span></p></body></html>"))
        self.name_label.setText(_translate("ContactAdmin", "Your name:"))
        self.sender_name_field.setPlaceholderText(_translate("ContactAdmin", "Please fill in carefully. (less 5 character)"))
        self.date_label.setText(_translate("ContactAdmin", "            Date:"))
        self.current_date_field.setText(_translate("ContactAdmin", "Thursday, 1/1/1970"))
        self.submit_btn.setText(_translate("ContactAdmin", "Submit"))
        self.submit_btn.setShortcut(_translate("ContactAdmin", "Return"))
        self.cancel_btn.setText(_translate("ContactAdmin", "Calcel"))
        self.cancel_btn.setShortcut(_translate("ContactAdmin", "Esc"))


