# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contact.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_contact_admin(object):
    def setupUi(self, contact_admin):
        contact_admin.setObjectName("contact_admin")
        contact_admin.resize(404, 480)
        self.centralwidget = QtWidgets.QWidget(contact_admin)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.email_title_label = QtWidgets.QLineEdit(self.centralwidget)
        self.email_title_label.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.email_title_label.setFont(font)
        self.email_title_label.setObjectName("email_title_label")
        self.gridLayout.addWidget(self.email_title_label, 1, 0, 1, 1)
        self.admin_email_label = QtWidgets.QLineEdit(self.centralwidget)
        self.admin_email_label.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.admin_email_label.setFont(font)
        self.admin_email_label.setObjectName("admin_email_label")
        self.gridLayout.addWidget(self.admin_email_label, 0, 0, 1, 1)
        self.email_content_label = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.email_content_label.setFont(font)
        self.email_content_label.setPlainText("")
        self.email_content_label.setObjectName("email_content_label")
        self.gridLayout.addWidget(self.email_content_label, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout_3.addWidget(self.name_label)
        self.required_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.required_label.setFont(font)
        self.required_label.setObjectName("required_label")
        self.horizontalLayout_3.addWidget(self.required_label)
        self.sender_name_field = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.sender_name_field.setFont(font)
        self.sender_name_field.setInputMask("")
        self.sender_name_field.setText("")
        self.sender_name_field.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sender_name_field.setObjectName("sender_name_field")
        self.horizontalLayout_3.addWidget(self.sender_name_field)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.date_label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_label_2.sizePolicy().hasHeightForWidth())
        self.date_label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.date_label_2.setFont(font)
        self.date_label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.date_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.date_label_2.setObjectName("date_label_2")
        self.horizontalLayout_4.addWidget(self.date_label_2)
        self.current_date_field = QtWidgets.QLineEdit(self.centralwidget)
        self.current_date_field.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.current_date_field.setFont(font)
        self.current_date_field.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.current_date_field.setObjectName("current_date_field")
        self.horizontalLayout_4.addWidget(self.current_date_field)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.submit_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.submit_btn.setFont(font)
        self.submit_btn.setObjectName("submit_btn")
        self.horizontalLayout.addWidget(self.submit_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        contact_admin.setCentralWidget(self.centralwidget)

        self.retranslateUi(contact_admin)
        self.cancel_btn.clicked.connect(contact_admin.close)
        QtCore.QMetaObject.connectSlotsByName(contact_admin)

    def retranslateUi(self, contact_admin):
        _translate = QtCore.QCoreApplication.translate
        contact_admin.setWindowTitle(_translate("contact_admin", "Send Email To Admin"))
        self.email_title_label.setText(_translate("contact_admin", "From FaceR Client: "))
        self.admin_email_label.setText(_translate("contact_admin", "yingjoy906@gmail.com"))
        self.name_label.setText(_translate("contact_admin", "Your name:"))
        self.required_label.setText(_translate("contact_admin", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">*</span></p></body></html>"))
        self.sender_name_field.setPlaceholderText(_translate("contact_admin", "Please fill in carefully. (less 5 character)"))
        self.date_label_2.setText(_translate("contact_admin", "Date:"))
        self.current_date_field.setText(_translate("contact_admin", "Thursday, 1/1/1970"))
        self.cancel_btn.setText(_translate("contact_admin", "Calcel"))
        self.cancel_btn.setShortcut(_translate("contact_admin", "Esc"))
        self.submit_btn.setText(_translate("contact_admin", "Submit"))
        self.submit_btn.setShortcut(_translate("contact_admin", "Return"))

